### ISSUE TITLE
support partial frame decoding

### ISSUE THREAD

**Issue by el3ment** [lilohuang/PyTurboJPEG#24]
libjpeg-turbo supports partial decoding, but that isn't exposed yet in PyTurboJPEG. it would be great if the decode function supported x, y, desiredWidth, and desiredHeight much like the java API does.

**Comment by lilohuang** [comment]
In fact, the TurboJPEG Java API doesn't support the so-called partial decoding. Actually, the x, y you mentioned indicates the x, y offset of the **destination** buffer rather than the **source** image. 

https://github.com/libjpeg-turbo/libjpeg-turbo/blob/master/java/org/libjpegturbo/turbojpeg/TJDecompressor.java#L653

A typical partial decoding means we can decode the **source** image for a specific region. So far, the TurboJPEG API doesn't support the partial decoding yet. See https://github.com/libjpeg-turbo/libjpeg-turbo/issues/313#issuecomment-457242676 for details.

I will add this new feature once the TurboJPEG supports the partial decoding. I cannot do anything at the current stage. Sorry about that.

**Comment by el3ment** [comment]
I misunderstood I guess -- https://github.com/libjpeg-turbo/libjpeg-turbo/blob/master/java/TJExample.java#L125 would seem to use a call to TJTransform before TJDecompressor to get cropped bytes, after which you decode

**Comment by el3ment** [comment]
I spent the day working on this -- I think this should be possible. I've gotten pretty close - but the cropped encoded bytes are incorrect (they are still zero) I expected a 4x increase in performance (that's what I've gotten from Nvidia's DALI using libjpeg-turbo for all of their CPU-based partial decoding), but I only see a 30% perf boost using this method right now.

Take a look at the "transform()" function -- it should return new jpeg bytes which correspond to the given crop after which you would decode.
[turbojpeg.zip](https://github.com/lilohuang/PyTurboJPEG/files/4332147/turbojpeg.zip)

**Comment by lilohuang** [comment]
libjpeg-turbo API supports partial decoding, TurboJPEG API not. If you want to use the PyTurboJPEG to do crop trick. I suggest you can take a look on this branch, https://github.com/BadgerTechnologies/PyTurboJPEG/blob/master/turbojpeg.py , it provides a crop() method for you doing crop and then decode, but  it's still different with the native partial decoding.
