### ISSUE TITLE
About Benchmark Details

### ISSUE THREAD

**Issue by austingg** [lilohuang/PyTurboJPEG#59]
hi， how about benchmark details? such as jpeg image information, cv2 build information? I wonder  the speed difference between when cv2 built with libjpegturbo.so and PyTurboJPEG

**Comment by lilohuang** [comment]
I think the cv2 build information has been provided, it's the so-called "prebuilt" version which means the pip installation (i.e. pip install opencv-python). Those benchmark were done serveral years ago so the number might be outdated. IIRC, the pre-built opencv-python I tested didn't enable libjpegturbo. You can also give a try to build an opencv-python with libjpegturbo from scratch to do your own benchmark. 

There is no guarantee that PyTurboJPEG is faster than opencv with libjpegturbo. However, the PyTuboJPEG provides much more features than opencv-python since PyTurboJPEG is a wrapper of libjpeg-turbo (TurboJPEG API), and you can unleash the power of libjpeg-turbo (e.g, lossless crop, fast scaling) and contiune to upgrade to newer libjpeg-turbo w/o rebuilding the library, it's very useful for a mission critical production enviroment. 

I would like to close this issue, please leave comment if it's not clear. Thanks.

**Comment by lilohuang** [comment]
@austingg  I think the cv2 build information has been provided, it's the so-called "prebuilt" version which means the pip installation (i.e. pip install opencv-python). Those benchmark numbers were done serveral years ago so the number might be outdated. IIRC, the pre-built opencv-python I tested didn't enable libjpegturbo. You can also give a try to build an opencv-python with libjpegturbo from scratch to do your own benchmark. Besides of that, the JPEG testing images were taken with my own modern MILC (SONY, Fujifilm) cameras. You can also find some sample images from their web site.

There is no guarantee that PyTurboJPEG is faster than opencv-python with libjpegturbo. However, the PyTuboJPEG provides much more features than opencv-python since PyTurboJPEG is a wrapper of libjpeg-turbo (TurboJPEG API), and you can unleash the power of libjpeg-turbo (e.g, lossless crop, fast scaling) and contiune to upgrade to newer libjpeg-turbo w/o rebuilding the library, it's very useful for a mission critical production enviroment from my expereince.

I would like to close this issue, please leave comment if it's not clear. Thanks.

**Comment by austingg** [comment]
OK, I know, many thanks. I will do some benchmark. Besides, we can get the build information by `cv2.getBuildInformation()`

**Comment by lilohuang** [comment]
@austingg  I understood how to get the build information, as I mentioned, those testing were done several years ago, and I don't have those information right now.

**Comment by austingg** [comment]
@lilohuang thanks
