### ISSUE TITLE
How to get encoded data without marker?

### ISSUE THREAD

**Issue by JrunDing** [lilohuang/PyTurboJPEG#73]
Hello! Thanks for offering this repository!
Due to my work, I need to get encoded data from BGR image without marker and then decode into BGR image. How can I realize it?

**Comment by lilohuang** [comment]
Hi @JrunDing

Thank you for using PyTurboJPEG. It is important to note that PyTurboJPEG library serves as a Python wrapper for TurboJPEG. Currently, TurboJPEG, which can be found at [TurboJPEG](https://github.com/libjpeg-turbo/libjpeg-turbo/blob/main/turbojpeg.h), does not provide a C API for extracting encoded data from a BGR image without JPEG markers. If you are looking for a function specifically designed to remove additional markers, including EXIF and ICC profile data, you may consider using the **crop_multiple** function, which allows you to exclude the copying of EXIF data when saving to a new image buffer.

```python
def crop_multiple(self, jpeg_buf, crop_parameters, background_luminance=1.0, gray=False, copynone=False):
        """Lossless crop and/or extension operations on jpeg image.
        Crop origin(s) needs be divisable by the MCU block size and inside
        the input image, or OSError: Invalid crop request is raised.

        Parameters
        ----------
        jpeg_buf: bytes
            Input jpeg image.
        crop_parameters: List[Tuple[int, int, int, int]]
            List of crop parameters defining start x and y origin and width
            and height of each crop operation.
        background_luminance: float
            Luminance level (0 -1 ) to fill background when extending image.
            Default to 1, resulting in white background.
        gray: bool
            Produce greyscale output
        copynone: bool
            True = do not copy EXIF data (False by default)

```
Best,
Lilo

**Comment by JrunDing** [comment]
Thank you for replying! I need to change the encoded data randomly and then decode it. Maybe only excluding EXIF is not enough. I have tried to use opencv, simplejpeg and PyTurboJEPG etc. to achieve this goal, but all failed due to wrong JPEG data which cant be decoded.

**Comment by lilohuang** [comment]
Hi @JrunDing,

If JPEG markers are removed, it would severely impact the decoding process of the JPEG image, and it might even become impossible to decode the image correctly. This is because JPEG markers contain crucial information and parameter settings that guide the decoder in correctly parsing and reconstructing the image data.

Certain essential markers, such as SOI (Start of Image) and EOI (End of Image), signify the starting and ending points of the JPEG image data. They are necessary components for the decoder to correctly interpret the image data. Other markers, like DQT (Define Quantization Table), SOF0 (Start of Frame, Baseline DCT), and DHT (Define Huffman Table), contain parameter settings and table information used in the compression and decompression processes. These parameters are vital for accurately decoding the JPEG image.

Therefore, if JPEG markers are removed, the decoder would be unable to recognize and parse the structure and compression method of the image data, resulting in an incorrect decoding of the JPEG image.

Thanks,
Lilo

**Comment by JrunDing** [comment]
Thanks very much. I know these. I want to reserve correct markers and only change encoded data. After that, I  will use the correct markers to replace changed markers and decode it. I want to know if this approach is feasible.

**Comment by lilohuang** [comment]
Your understanding of these fundamental concepts is already commendable. However, the topic of discussion exceeds the capabilities of PyTurboJPEG. It is advisable to explore alternative Python implementations of JPEG decoders/encoders and adapt their logic while preserving the essential JPEG markers to accomplish your objective. For instance, you can refer to the following GitHub repository: https://github.com/ghallak/jpeg-python. Best of luck in your endeavors! :)
