### ISSUE TITLE
Corrupt JPEG data: 608 extraneous bytes before marker 0xfe

### ISSUE THREAD

**Issue by iridris** [lilohuang/PyTurboJPEG#77]
I'm getting an error message logged in Home Assistant whenever it loads a dashboard with one of my camera streams. I've attempted to enable debug logging, but I don't seem to get any additional log output than this.

Log message:
```
2024-06-02 07:27:38.735 WARNING (MainThread) [py.warnings] /usr/local/lib/python3.12/site-packages/turbojpeg.py:901: UserWarning: Corrupt JPEG data: 608 extraneous bytes before marker 0xfe
  warnings.warn(self.__get_error_string(handle))
```

This has been occurring for quite a while for me, I'm just now getting around to opening an issue about it.

**Comment by lilohuang** [comment]
Hi @iridris ,

Please ensure that you are using the latest version of the libjpeg-turbo library (3.0.1) when reporting this issue.

As you know, PyTurboJPEG is a Python wrapper for the libjpeg-turbo library (TurboJPEG API). PyTurboJPEG attempts to retrieve error strings from the libjpeg-turbo library whenever an error occurs. The message "Corrupt JPEG data: 608 extraneous bytes before marker 0xfe" is exactly the error message provided by the libjpeg-turbo library, and we cannot obtain any additional information beyond this.

This error might be due to a corrupted JPEG input from an IP camera or a similar live streaming device. It is a benign warning, and you can choose to either disregard it or report the issue to the IP camera or live streaming source provider.

I will close this issue as PyTurboJPEG cannot offer any further enhancements for this matter.

Best,
Lilo
